superadmin_workgroups:
  - dlss:exhibits-admin
default_contact_email: exhibits-feedback@lists.stanford.edu
geonames_username: ''
stacks:
  iiif_url: 'https://stacks.stanford.edu/image/iiif'
  file_url: 'https://stacks.stanford.edu/file'

purl:
  iiif_manifest_url: 'https://purl.stanford.edu/%{druid}/iiif/manifest.json'

action_mailer:
  default_options:
    from: "example-team@example.com"
  default_url_options:
    host: "example.com"
